from django.urls import path

from kitchen_restaurant.views import (
    index,
    DishTypeListView,
    DishListView,
    CookListView,
    DishDetailView,
    DishTypeDetailView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "cook/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "dish_types/<int:pk>",
        DishTypeDetailView.as_view(),
        name="dish-type-detail"
    ),
    path(
        "dish/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "cook/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "dish_types/create",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"),
    path(
        "dish/create",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dish/<int:pk>/update",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dish/<int:pk>/delete",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "cook/create",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cook/<int:pk>/update",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cook/<int:pk>/delete",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),

]
app_name = "kitchen_restaurant"
